In [3]:
!pip install -q torch torchvision torchaudio
!pip install -q transformers==4.44.2 datasets==2.21.0 accelerate==0.33.0
!pip install -q peft==0.12.0 trl==0.10.1 bitsandbytes==0.43.3
!pip install -q huggingface_hub

In [1]:
!pip install unsloth
!pip install --force-reinstall --no-cache-dir --no-deps \
  git+https://github.com/unslothai/unsloth.git

Requirement already satisfied: unsloth in /usr/local/lib/python3.12/dist-packages (2026.3.5)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.1)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.12.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from unsloth) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth) (0.4.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->unsloth) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->unsloth) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->unsloth) (0.1.2)
Collecting git+https://github.com/unslothai/unsloth.git
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-req-build-2zy2wc3e
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-req-build-2zy2wc3e
  Resolved https://github.com/unslothai/unsloth.git to commit 93ab09d19506fa2f652b89f9f0c4caf8dd85b7e2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: unsloth
  Building wheel for unsloth (pyproject.toml) ... done
  Created wheel for unsloth: filename=unsloth-2026.3.5-py3-none-any.whl size=29234458 sha256=4fde57bb6efd54b5640dd4bbca3a4645e7af7e97d57b11bcd8898a3f3c2dd7ba
  Stored in directory: /tmp/pip-ephem-wheel-cache-uwp_ypra/wheels/60/3e/1f/e576c07051d90cf64b6a41434d87ccf4db33fafd5343bf5de0
Successfully built unsloth
Installing collected packages: unsloth
  Attempting uninstall: unsloth
    Found existing installation: unsloth 2026.3.5
    Uninstalling unsloth-2026.3.5:
      Successfully uninstalled unsloth-2026.3.5
Successfully installed unsloth-2026.3.5

In [3]:
!pip install --upgrade --no-cache-dir --no-deps unsloth unsloth_zoo
!pip install "transformers>=4.51.0" --upgrade

Requirement already satisfied: unsloth in /usr/local/lib/python3.12/dist-packages (2026.3.5)
Requirement already satisfied: unsloth_zoo in /usr/local/lib/python3.12/dist-packages (2026.3.4)
Collecting transformers>=4.51.0
  Using cached transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub<2.0,>=1.3.0 (from transformers>=4.51.0)
  Using cached huggingface_hub-1.7.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.51.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.51.0) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.51.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.51.0) (2025.11.3)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers>=4.51.0)
  Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.51.0) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.51.0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.51.0) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=4.51.0) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=4.51.0) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=4.51.0) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=4.51.0) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=4.51.0) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.51.0) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.51.0) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.51.0) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.51.0) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=4.51.0) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=4.51.0) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=4.51.0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=4.51.0) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=4.51.0) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers>=4.51.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers>=4.51.0) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers>=4.51.0) (0.1.2)
Using cached transformers-5.3.0-py3-none-any.whl (10.7 MB)
Using cached huggingface_hub-1.7.1-py3-none-any.whl (616 kB)
Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 0.36.2
    Uninstalling huggingface_hub-0.36.2:
      Successfully uninstalled huggingface_hub-0.36.2
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.19.1
    Uninstalling tokenizers-0.19.1:
      Successfully uninstalled tokenizers-0.19.1
  Attempting uninstall: transformers
    Found existing installation: transformers 4.44.2
    Uninstalling transformers-4.44.2:
      Successfully uninstalled transformers-4.44.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unsloth-zoo 2026.3.4 requires accelerate>=0.34.1, but you have accelerate 0.33.0 which is incompatible.
unsloth-zoo 2026.3.4 requires datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1, but you have datasets 2.21.0 which is incompatible.
unsloth-zoo 2026.3.4 requires peft!=0.11.0,>=0.18.0, but you have peft 0.12.0 which is incompatible.
unsloth-zoo 2026.3.4 requires trl!=0.19.0,<=0.24.0,>=0.18.2, but you have trl 0.10.1 which is incompatible.
Successfully installed huggingface-hub-1.7.1 tokenizers-0.22.2 transformers-5.3.0

In [2]:
!pip uninstall -y bitsandbytes
!pip install bitsandbytes --upgrade -q

Found existing installation: bitsandbytes 0.43.3
Uninstalling bitsandbytes-0.43.3:
  Successfully uninstalled bitsandbytes-0.43.3

In [4]:
!pip install accelerate -q

In [6]:
!pip install accelerate -q
!pip install --upgrade unsloth unsloth_zoo -q

In [1]:
from unsloth import FastLanguageModel
import torch

print(f"GPU : {torch.cuda.get_device_name(0)}")
print(f"VRAM : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} Go")
print("✅ Unsloth OK !")

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
GPU : Tesla T4
VRAM : 15.6 Go
✅ Unsloth OK !

In [2]:
from unsloth import FastLanguageModel

max_seq_length = 2048
load_in_4bit = True

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = None,
    load_in_4bit = load_in_4bit,
)

# Configuration LoRA
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 32,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 42,
)

model.print_trainable_parameters()

==((====))==  Unsloth 2026.3.5: Fast Mistral patching. Transformers: 5.3.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/4.14G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/157 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/587k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/446 [00:00<?, ?B/s]

Unsloth 2026.3.5 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

trainable params: 41,943,040 || all params: 7,289,966,592 || trainable%: 0.5754

In [3]:
from datasets import load_dataset
from unsloth.chat_templates import get_chat_template, train_on_responses_only

# Appliquer le template ChatML au tokenizer
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "chatml",
)

# Fonction qui formate chaque exemple en texte ChatML
def formatting_prompts_func(examples):
    convos = examples["messages"]
    texts = [
        tokenizer.apply_chat_template(
            convo,
            tokenize = False,
            add_generation_prompt = False
        )
        for convo in convos
    ]
    return {"text": texts}

# Charger ton dataset
dataset = load_dataset("json", data_files="/content/loodo_dataset.jsonl", split="train")

# Appliquer le formatage
dataset = dataset.map(formatting_prompts_func, batched=True)

# Vérification — affiche le premier exemple formaté
print("Nombre d'exemples :", len(dataset))
print("\n--- Premier exemple formaté ---")
print(dataset[0]["text"][:500])

Unsloth: Will map <|im_end|> to EOS = </s>.

Generating train split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/51 [00:00<?, ? examples/s]

Nombre d'exemples : 51

--- Premier exemple formaté ---
<|im_start|>system
Tu es Loodo, un coach personnel bienveillant et direct spécialisé en productivité, motivation et organisation. Tu donnes des conseils concrets et actionnables. Tu es empathique mais tu pousses l'utilisateur à agir.<|im_end|>
<|im_start|>user
J'arrive pas à me concentrer, je procrastine depuis 2h<|im_end|>
<|im_start|>assistant
2h de procrastination, ça arrive à tout le monde. Pas de culpabilité, on passe en mode action. Voilà ce que tu vas faire maintenant : choisis UNE seule

In [6]:
from transformers import TextStreamer

messages_test = [
    {"role": "system", "content": "Tu es Loodo, un coach bienveillant spécialisé en motivation et organisation personnelle."},
    {"role": "user", "content": "J'arrive pas à me concentrer depuis 2 heures, je procrastine sur tout."}
]

inputs = tokenizer.apply_chat_template(
    messages_test,
    tokenize = True,
    add_generation_prompt = True,
    return_tensors = "pt"
).to("cuda")

streamer = TextStreamer(tokenizer, skip_prompt=True)

print("=== RÉPONSE AVANT FINE-TUNING ===\n")
with torch.no_grad():
    _ = model.generate(
        input_ids = inputs,
        streamer = streamer,
        max_new_tokens = 200,
        temperature = 0.7,
        do_sample = True,
        use_cache = False,  # ← on désactive le cache KV
    )

Both `max_new_tokens` (=200) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== RÉPONSE AVANT FINE-TUNING ===

/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)

Cela peut être dû à plusieurs facteurs, mais l'une des causes les plus courantes est l'anxiété chronique. Vous pouvez essayer de vous poser des questions telles que "Qu'est-ce qui m'empêche de me concentrer ?", "Quelle est la pire chose qui peut arriver si je ne suis pas distrait maintenant ?" et "Quand je suis concentré, je peux réussir à accomplir ce qui est important pour moi. Quand je suis distrait, je me sens perdu et je n'ai pas de réussite". En répondant à ces questions, vous pouvez comprendre les causes de votre distraction.<|im_end|>

Réponces du  model Mistral-07 avent Fine tuning:
Cela peut être dû à plusieurs facteurs, mais l'une des causes les plus courantes est l'anxiété chronique. Vous pouvez essayer de vous poser des questions telles que "Qu'est-ce qui m'empêche de me concentrer ?", "Quelle est la pire chose qui peut arriver si je ne suis pas distrait maintenant ?" et "Quand je suis concentré, je peux réussir à accomplir ce qui est important pour moi. Quand je suis distrait, je me sens perdu et je n'ai pas de réussite". En répondant à ces questions, vous pouvez comprendre les causes de votre distraction.<|im_end|>

In [8]:
from trl import SFTTrainer
from transformers import TrainingArguments

# Reformatage manuel avec les bons tokens
def formatting_func(example):
    text = ""
    for msg in example["messages"]:
        role = msg["role"]
        content = msg["content"]
        text += f"<|im_start|>{role}\n{content}<|im_end|>\n"
    text += "<|im_start|>assistant\n"
    return {"text": text}

dataset_fixed = dataset.map(formatting_func)

# Vérifie que ça ressemble à ça
print(dataset_fixed[0]["text"][:300])

Map:   0%|          | 0/51 [00:00<?, ? examples/s]

<|im_start|>system
Tu es Loodo, un coach personnel bienveillant et direct spécialisé en productivité, motivation et organisation. Tu donnes des conseils concrets et actionnables. Tu es empathique mais tu pousses l'utilisateur à agir.<|im_end|>
<|im_start|>user
J'arrive pas à me concentrer, je procra

In [10]:
from trl import SFTTrainer
from transformers import TrainingArguments

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset_fixed,
    dataset_text_field = "text",
    max_seq_length = 2048,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        num_train_epochs = 3,
        learning_rate = 2e-4,
        fp16 = True,
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 42,
        output_dir = "loodo_outputs",
    ),
)

trainer_stats = trainer.train()

print(f"\n✅ Training terminé !")
print(f"Loss finale : {trainer_stats.training_loss:.4f}")

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/51 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 51 | Num Epochs = 3 | Total steps = 21
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040 of 7,289,966,592 (0.58% trained)

✅ Training terminé !
Loss finale : 0.9451

✅ Training terminé !
Loss finale : 0.9451

In [11]:
messages_test = [
    {"role": "system", "content": "Tu es Loodo, un coach bienveillant spécialisé en motivation et organisation personnelle."},
    {"role": "user", "content": "J'arrive pas à me concentrer depuis 2 heures, je procrastine sur tout."}
]

inputs = tokenizer.apply_chat_template(
    messages_test,
    tokenize = True,
    add_generation_prompt = True,
    return_tensors = "pt"
).to("cuda")

streamer = TextStreamer(tokenizer, skip_prompt=True)

print("=== RÉPONSE APRÈS FINE-TUNING ===\n")
with torch.no_grad():
    _ = model.generate(
        input_ids = inputs,
        streamer = streamer,
        max_new_tokens = 200,
        temperature = 0.7,
        do_sample = True,
        use_cache = False,
    )

Both `max_new_tokens` (=200) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== RÉPONSE APRÈS FINE-TUNING ===

/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)

Procrastination c'est souvent le signe que le cerveau a besoin de direction. On va créer un plan d'action de 2 minutes, pas un plan de 2 heures — le cerveau ne s'engage pas avec ça. Dis-moi ce que tu dois faire aujourd'hui en 3 mots maximum. Ensuite, on découpe ce incompletable en 3 à 5 actions concrètes de 5 minutes chacune. On part de l'imprévisible au prédicable. Par exemple : 'Rédiger le mémo pour la réunion demain' devient 'Ouvre Google Docs, écrit le titre, développe le point 1 en 2 lignes, enregistre et ferme — 5 minutes.' Le cerveau se dit 'je peux ça'.<|im_end|>

réponce après fine tuning :

Procrastination c'est souvent le signe que le cerveau a besoin de direction. On va créer un plan d'action de 2 minutes, pas un plan de 2 heures — le cerveau ne s'engage pas avec ça. Dis-moi ce que tu dois faire aujourd'hui en 3 mots maximum. Ensuite, on découpe ce incompletable en 3 à 5 actions concrètes de 5 minutes chacune. On part de l'imprévisible au prédicable. Par exemple : 'Rédiger le mémo pour la réunion demain' devient 'Ouvre Google Docs, écrit le titre, développe le point 1 en 2 lignes, enregistre et ferme — 5 minutes.' Le cerveau se dit 'je peux ça'.<|im_end|>

In [12]:
# Sauvegarde de l'adaptateur LoRA en local
model.save_pretrained("loodo_lora_v1")
tokenizer.save_pretrained("loodo_lora_v1")

print("✅ Modèle sauvegardé dans /content/loodo_lora_v1")

✅ Modèle sauvegardé dans /content/loodo_lora_v1

In [13]:
from huggingface_hub import login

login(token='API KEY')

# Push le modèle
model.push_to_hub("Pirodax/loodo-mistral-7b-coach-v1")
tokenizer.push_to_hub("Pirodax/loodo-mistral-7b-coach-v1")

print("✅ Modèle pushé sur HuggingFace !")

README.md:   0%|          | 0.00/575 [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   0%|          |  561kB /  168MB

Saved model to https://huggingface.co/Pirodax/loodo-mistral-7b-coach-v1
✅ Modèle pushé sur HuggingFace !

In [14]:
from datasets import load_dataset

dataset_v2 = load_dataset("json", data_files="/content/loodo_dataset_150.jsonl", split="train")
dataset_v2 = dataset_v2.map(formatting_func)

print(f"Nombre d'exemples : {len(dataset_v2)}")
print(dataset_v2[0]["text"][:300])

Generating train split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Nombre d'exemples : 150
<|im_start|>system
Tu es Loodo, un coach personnel bienveillant et direct spécialisé en productivité, motivation et organisation. Tu donnes des conseils concrets et actionnables. Tu es empathique mais tu pousses l'utilisateur à agir.<|im_end|>
<|im_start|>user
J'arrive pas à me concentrer, je procra

Deux changements par rapport à v1 : learning_rate baissé à 1e-4 car le modèle a déjà appris une base, et warmup_steps monté à 10 pour le dataset plus grand.

In [15]:
trainer_v2 = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset_v2,
    dataset_text_field = "text",
    max_seq_length = 2048,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 10,
        num_train_epochs = 3,
        learning_rate = 1e-4,
        fp16 = True,
        logging_steps = 5,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 42,
        output_dir = "loodo_outputs_v2",
    ),
)

trainer_stats_v2 = trainer_v2.train()

print(f"\n✅ Training v2 terminé !")
print(f"Loss finale : {trainer_stats_v2.training_loss:.4f}")

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/150 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 150 | Num Epochs = 3 | Total steps = 57
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040 of 7,289,966,592 (0.58% trained)

✅ Training v2 terminé !
Loss finale : 0.4872

✅ Training v2 terminé !
Loss finale : 0.4872

 à noter : la qualité et quantité du dataset impacte plus que les hyperparamètres.

In [16]:
messages_test = [
    {"role": "system", "content": "Tu es Loodo, un coach bienveillant spécialisé en motivation et organisation personnelle."},
    {"role": "user", "content": "J'arrive pas à me concentrer depuis 2 heures, je procrastine sur tout."}
]

inputs = tokenizer.apply_chat_template(
    messages_test,
    tokenize = True,
    add_generation_prompt = True,
    return_tensors = "pt"
).to("cuda")

streamer = TextStreamer(tokenizer, skip_prompt=True)

print("=== RÉPONSE APRÈS FINE-TUNING V2 ===\n")
with torch.no_grad():
    _ = model.generate(
        input_ids = inputs,
        streamer = streamer,
        max_new_tokens = 200,
        temperature = 0.7,
        do_sample = True,
        use_cache = False,
    )

Both `max_new_tokens` (=200) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== RÉPONSE APRÈS FINE-TUNING V2 ===

/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)

2 heures de perte de concentration, c'est souvent le signal que ton cerveau a besoin d'une pause. Pas d'accuse, pas de culpabilité — tu as travaillé avant. Fais une micro-pause de 5 minutes : marche, station debout, stretching, respiration. Puis relance sur une micro-tâche précise de moins de 5 minutes. Travaller fatigué te coûte plus de temps au final.<|im_end|>

Reponse de la V2

2 heures de perte de concentration, c'est souvent le signal que ton cerveau a besoin d'une pause. Pas d'accuse, pas de culpabilité — tu as travaillé avant. Fais une micro-pause de 5 minutes : marche, station debout, stretching, respiration. Puis relance sur une micro-tâche précise de moins de 5 minutes. Travaller fatigué te coûte plus de temps au final.<|im_end|>

Pourquoi il dit "tu as travaillé avant" :
Le modèle ne sait pas que tu procrastines depuis 2h sans avoir travaillé. Il a appris dans son dataset que quand quelqu'un dit "je n'arrive pas à me concentrer", c'est souvent après une période de travail. Il hallucine une hypothèse basée sur les patterns statistiques de tes données d'entraînement — pas sur la réalité de la conversation.
C'est une limite fondamentale du fine-tuning sur peu de données : le modèle généralise parfois trop vite et invente du contexte.

In [17]:
model.save_pretrained("loodo_lora_v2")
tokenizer.save_pretrained("loodo_lora_v2")
print("✅ Modèle v2 sauvegardé localement")

✅ Modèle v2 sauvegardé localement

In [ ]:
from huggingface_hub import login

login(token='API KEY')

# Push le modèle
model.push_to_hub("Pirodax/loodo-mistral-7b-coach-v1")
tokenizer.push_to_hub("Pirodax/loodo-mistral-7b-coach-v1")

print("✅ Modèle pushé sur HuggingFace !")

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   0%|          |  560kB /  168MB

Saved model to https://huggingface.co/Pirodax/loodo-mistral-7b-coach-v1

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

✅ Modèle pushé sur HuggingFace !

In [ ]:
from huggingface_hub import login
from huggingface_hub import ModelCard

login(token='API kEY')

card_content = """
# loodo-mistral-7b-coach-fr

Mistral 7B fine-tuné en QLoRA sur un dataset de coaching motivation/organisation en français, pour l'assistant IA de [Loodo](https://loodo.app).

## Résultats
| Version | Dataset | Loss |
|---------|---------|------|
| Baseline | 0 exemples | - |
| v1 | 51 exemples | 0.94 |
| v2 | 150 exemples | 0.48 |

## Méthode
- Fine-tuning QLoRA 4-bit avec Unsloth
- LoRA rank=16, alpha=32
- 3 epochs, learning rate 1e-4
- GPU : Tesla T4 (Google Colab)

## Usage
```python
from unsloth import FastLanguageModel
model, tokenizer = FastLanguageModel.from_pretrained("ton_username/loodo-mistral-7b-coach-fr")
```

## Limitations
Dataset synthétique généré par IA — hallucinations résiduelles possibles sur le contexte utilisateur.
"""

card = ModelCard(card_content)
card.push_to_hub("Pirodax/loodo-mistral-7b-coach-v1")
print("✅ Model card ajoutée !")

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

✅ Model card ajoutée !

In [28]:
import torch

print("=== MÉTRIQUES GPU ===\n")

# VRAM utilisée pendant le training
vram_used = torch.cuda.max_memory_allocated() / 1e9
vram_total = torch.cuda.get_device_properties(0).total_memory / 1e9
print(f"VRAM peak utilisée : {vram_used:.2f} Go / {vram_total:.1f} Go")
print(f"Utilisation VRAM : {(vram_used/vram_total)*100:.1f}%")

# Temps et vitesse d'entraînement
total_steps = trainer_stats_v2.global_step
runtime = trainer_stats_v2.metrics["train_runtime"]
samples_per_sec = trainer_stats_v2.metrics["train_samples_per_second"]
steps_per_sec = trainer_stats_v2.metrics["train_steps_per_second"]

print(f"\nTemps total d'entraînement : {runtime/60:.1f} minutes")
print(f"Nombre de steps : {total_steps}")
print(f"Vitesse : {samples_per_sec:.2f} exemples/sec")
print(f"Steps/sec : {steps_per_sec:.2f}")

# Paramètres entraînés
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"\nParamètres totaux : {total_params/1e9:.2f}B")
print(f"Paramètres entraînés (LoRA) : {trainable_params/1e6:.1f}M")
print(f"Ratio entraîné : {(trainable_params/total_params)*100:.2f}%")

=== MÉTRIQUES GPU ===

VRAM peak utilisée : 7.75 Go / 15.6 Go
Utilisation VRAM : 49.6%

Temps total d'entraînement : 5.1 minutes
Nombre de steps : 57
Vitesse : 1.48 exemples/sec
Steps/sec : 0.19

Paramètres totaux : 3.80B
Paramètres entraînés (LoRA) : 41.9M
Ratio entraîné : 1.10%

Comparatif des versions :

In [30]:
from IPython.display import HTML

chart_html = """
<div style="padding: 1rem 0;">
<div style="display: flex; flex-wrap: wrap; gap: 12px; margin-bottom: 1.5rem;">
  <div style="flex: 1; min-width: 140px; background: #f5f5f5; border-radius: 8px; padding: 1rem;">
    <p style="font-size: 13px; color: #666; margin: 0 0 4px;">Loss finale</p>
    <p style="font-size: 22px; font-weight: 500; margin: 0;">0.94 → 0.48</p>
    <p style="font-size: 12px; color: #2d8a4e; margin: 4px 0 0;">-49%</p>
  </div>
  <div style="flex: 1; min-width: 140px; background: #f5f5f5; border-radius: 8px; padding: 1rem;">
    <p style="font-size: 13px; color: #666; margin: 0 0 4px;">Dataset</p>
    <p style="font-size: 22px; font-weight: 500; margin: 0;">51 → 150</p>
    <p style="font-size: 12px; color: #185fa5; margin: 4px 0 0;">+194%</p>
  </div>
  <div style="flex: 1; min-width: 140px; background: #f5f5f5; border-radius: 8px; padding: 1rem;">
    <p style="font-size: 13px; color: #666; margin: 0 0 4px;">Steps</p>
    <p style="font-size: 22px; font-weight: 500; margin: 0;">21 → 57</p>
    <p style="font-size: 12px; color: #185fa5; margin: 4px 0 0;">+171%</p>
  </div>
  <div style="flex: 1; min-width: 140px; background: #f5f5f5; border-radius: 8px; padding: 1rem;">
    <p style="font-size: 13px; color: #666; margin: 0 0 4px;">VRAM utilisée</p>
    <p style="font-size: 22px; font-weight: 500; margin: 0;">49.6%</p>
    <p style="font-size: 12px; color: #666; margin: 4px 0 0;">7.75 / 15.6 Go</p>
  </div>
</div>

<div style="display: flex; flex-wrap: wrap; gap: 1.5rem;">
  <div style="flex: 1; min-width: 260px; position: relative; height: 220px;">
    <p style="font-size: 13px; color: #666; margin: 0 0 8px;">Loss finale</p>
    <canvas id="lossChart"></canvas>
  </div>
  <div style="flex: 1; min-width: 260px; position: relative; height: 220px;">
    <p style="font-size: 13px; color: #666; margin: 0 0 8px;">Taille du dataset</p>
    <canvas id="datasetChart"></canvas>
  </div>
  <div style="flex: 1; min-width: 260px; position: relative; height: 220px;">
    <p style="font-size: 13px; color: #666; margin: 0 0 8px;">Temps d'entraînement (min)</p>
    <canvas id="timeChart"></canvas>
  </div>
</div>

<p style="font-size: 12px; color: #888; margin: 1rem 0 0; border-top: 1px solid #eee; padding-top: 0.75rem;">
  LoRA rank=16 · alpha=32 · QLoRA 4-bit · Tesla T4 · Unsloth 2026.3.5 · 1.10% paramètres entraînés
</p>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js"></script>
<script>
const barOpts = (data, labels, colors) => ({
  type: 'bar',
  data: {
    labels: labels,
    datasets: [{ data: data, backgroundColor: colors, borderRadius: 6, borderSkipped: false }]
  },
  options: {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { grid: { display: false }, ticks: { color: '#888' } },
      y: { grid: { color: 'rgba(128,128,128,0.15)' }, ticks: { color: '#888' } }
    }
  }
});

new Chart(document.getElementById('lossChart'), barOpts([0.94, 0.48], ['v1', 'v2'], ['#B5D4F4', '#378ADD']));
new Chart(document.getElementById('datasetChart'), barOpts([51, 150], ['v1', 'v2'], ['#9FE1CB', '#1D9E75']));
new Chart(document.getElementById('timeChart'), barOpts([1.9, 4.95], ['v1 (1:54)', 'v2 (4:57)'], ['#FAC775', '#BA7517']));
</script>
"""

display(HTML(chart_html))